// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// classtableC
List classtableC(LogicalVector pred, LogicalVector crit);
RcppExport SEXP FFTrees_classtableC(SEXP predSEXP, SEXP critSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type pred(predSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type crit(critSEXP);
    rcpp_result_gen = Rcpp::wrap(classtableC(pred, crit));
    return rcpp_result_gen;
END_RCPP
}
