---
title: "Explore_NAs_CHARACTER"
author: "Jelena Meyer"
date: "2023-06-12"
output: html_document
---
```{r setup, include = FALSE}
# load packages
library(dplyr)
library(tidyverse)

```

# ONLY CHARACTER VARIABLES, NAs added at RANDOM

```{r build-data-set-with-only-character-predictors, echo = FALSE}
# Preparations:
# Build subset of data with only character variables and criterion: 
heart.cat <- heart.train %>%
  select(where(is.character), diagnosis)
 
# For NA = 100% also build character subset for test data: 
heart.cat.test <- heart.test %>%
  select(where(is.character), diagnosis)

```



```{r Baseline-only-character-predictors}

#Build tree for normal data set:
heart.fft.cat <- FFTrees(formula = diagnosis ~.,
                     data = heart.cat,
                     main = "Heart Disease",
                     decision.labels = c("Healthy", "Diseased"))

plot(heart.fft.cat)

```

```{r Data-with-25pc-NAs-character}

# Preparations:

# get all names of variables but exclude criterion: 
column_names_heart <- colnames(heart.cat)
column_names_heart <- column_names_heart[column_names_heart != 'diagnosis']

# in total 25% should be NAs in the end, split equally over all variables: 
num_columns <- length(column_names_heart)
pc_per_row_25 <- 0.25


# create vector with that pc for number of rows:
pc_vector_25 <- rep(pc_per_row_25, times = num_columns)

# apply replace_values function and thereby create new data frames:

# set seed for being able to replicate results:
set.seed(13)

# 25% NAs in data set:
heart_NA_25 <- replace_values(data = heart.cat, cols = column_names_heart, amount = pc_vector_25)


# build best tree. 25% NAs (standard function)
heart.fft_NA_25 <- FFTrees(formula = diagnosis ~.,
                     data = heart_NA_25,
                     main = "Heart Disease",
                     decision.labels = c("Healthy", "Diseased"))


plot(heart.fft_NA_25)


```




```{r  Data-with-50pc-NAs-character}

# Preparations:

# get all names of variables but exclude criterion: 
column_names_heart <- colnames(heart.cat)
column_names_heart <- column_names_heart[column_names_heart != 'diagnosis']

# in total 50% should be NAs in the end, split equally over all variables: 
num_columns <- length(column_names_heart)
pc_per_row_50 <- 0.50

# create vector with that pc for number of rows:
pc_vector_50 <- rep(pc_per_row_50, times = num_columns)

# apply replace_values function and thereby create new data frames:

# set seed for being able to replicate results:
set.seed(133)

# 50% NAs in data set:
heart_NA_50 <- replace_values(data = heart.cat, cols = column_names_heart, amount = pc_vector_50)



# build best tree, 50% NAs (standard function)
heart.fft_NA_50 <- FFTrees(formula = diagnosis ~.,
                     data = heart_NA_50,
                     main = "Heart Disease",
                     decision.labels = c("Healthy", "Diseased"),
                     do.comp = FALSE)



plot(heart.fft_NA_50)



```



```{r Data-with-75pc-NAs-character}

# Preparations:

# get all names of variables but exclude criterion: 
column_names_heart <- colnames(heart.cat)
column_names_heart <- column_names_heart[column_names_heart != 'diagnosis']

# in total 75% should be NAs in the end, split equally over all variables: 
num_columns <- length(column_names_heart)
pc_per_row_75 <- 0.75

# create vector with that pc for number of rows:
pc_vector_75 <- rep(pc_per_row_75, times = num_columns)

# apply replace_values function and thereby create new data frames:

# set seed for being able to replicate results:
set.seed(1333)

# 75% NAs in data set:
heart_NA_75 <- replace_values(data = heart.cat, cols = column_names_heart, amount = pc_vector_75)



# build best tree, 75% NAs (standard function)
heart.fft_NA_75 <- FFTrees(formula = diagnosis ~.,
                     data = heart_NA_75,
                     main = "Heart Disease",
                     decision.labels = c("Healthy", "Diseased"),
                     do.comp = FALSE)


plot(heart.fft_NA_75)


```


```{r Data-with-100pc-NAs-in-TESTDATA-character}

# Preparations:

# get all names of variables but exclude criterion: 
column_names_heart <- colnames(heart.cat.test)
column_names_heart <- column_names_heart[column_names_heart != 'diagnosis']

# in total 100% per row should be NAs in the end: 
per_row_100 <- nrow(heart.cat.test)


# create vector with number of rows:
num_columns <- length(column_names_heart)
vector_100 <- rep(per_row_100, times = num_columns)

# apply replace_values function and thereby create new data frames:

# set seed for being able to replicate results:
set.seed(13333)

# 100% NAs in data set:
heart_NA_100 <- replace_values(data = heart.cat.test, cols = column_names_heart, amount = vector_100)



# build best tree, 100% NAs (standard function)
heart.fft_NA_100 <- FFTrees(formula = diagnosis ~.,
                     data = heart.cat,
                     data.test = heart_NA_100,
                     main = "Heart Disease",
                     decision.labels = c("Healthy", "Diseased"),
                     do.comp = FALSE)


plot(heart.fft_NA_100, data = "test") # it shows the expected behaviour.


```


# ONLY CHARACTER VARIABLES, NAs added SYSTEMATICALLY


```{r Data-with-25pc-NAs-character-SYSTEMATICALLY}

# Preparations: 

# get all names of variables but exclude criterion: 
column_names_heart <- colnames(heart.cat)
column_names_heart <- column_names_heart[column_names_heart != 'diagnosis']

# in total 25% should be NAs in the end: 
num_columns <- length(column_names_heart)
pc_per_row_25 <- 0.25


# create vector with that pc for number of rows:
pc_vector_25 <- rep(pc_per_row_25, times = num_columns)

# prepare list for systematic replacement of values with a certain level:
# in total 25% of the variable should be converted to NAs, all in one level:
nas <- round(0.25*(nrow(heart.cat)))

#create list
systematic_replacement <- list("cp" = list("a" = nas), "restecg" = list("normal" = nas), "slope" = list("up" = nas), "thal" = list("normal" = nas))
  
  
# apply replace_values function and thereby create new data frames:

# set seed for being able to replicate results:
set.seed(13)

# 25% NAs in data set:
heart_NA_25 <- replace_values(data = heart.cat, cols = column_names_heart, amount = pc_vector_25, levels_amount = systematic_replacement)


# build best tree. 25% NAs (standard function)
heart.fft_NA_25 <- FFTrees(formula = diagnosis ~.,
                     data = heart_NA_25,
                     main = "Heart Disease",
                     decision.labels = c("Healthy", "Diseased"))


plot(heart.fft_NA_25) # presumably correct hypothesis, stays as good as without NAs.


```


```{r Data-with-50pc-NAs-character-SYSTEMATICALLY}

# Preparations:

# get all names of variables but exclude criterion: 
column_names_heart <- colnames(heart.cat)
column_names_heart <- column_names_heart[column_names_heart != 'diagnosis']

# in total 50% should be NAs in the end, split equally over all variables: 
num_columns <- length(column_names_heart)
pc_per_row_50 <- 0.5

# create vector with that pc for number of rows:
pc_vector_50 <- rep(pc_per_row_50, times = num_columns)


# prepare list for systematic replacement of values with a certain level:
# in total 25% of the variable should be converted to NAs, all in one level:
nas <- round(0.5*(nrow(heart.cat)))

#create list
systematic_replacement <- list("cp" = list("a" = nas), "restecg" = list("normal" = nas), "slope" = list("up" = nas), "thal" = list("normal" = nas))
# apply replace_values function and thereby create new data frames:

# set seed for being able to replicate results:
set.seed(1133)

# 50% NAs in data set:
heart_NA_50 <- replace_values(data = heart.cat, cols = column_names_heart, amount = pc_vector_50)



# build best tree, 50% NAs (standard function)
heart.fft_NA_50 <- FFTrees(formula = diagnosis ~.,
                     data = heart_NA_50,
                     main = "Heart Disease",
                     decision.labels = c("Healthy", "Diseased"),
                     do.comp = FALSE)



plot(heart.fft_NA_50) # against predictions, worsens! So far no idea why it constructs another tree and therefore shows a weaker performance!



```

