---
title: "Explore_NAs_basic"
author: "Jelena Meyer"
date: "2023-06-12"
output: html_document
---

```{r Baseline}

#Build tree for normal data set:
heart.fft <- FFTrees(formula = diagnosis ~.,
                     data = heart.train,
                     main = "Heart Disease",
                     decision.labels = c("Healthy", "Diseased"))

```

```{r Data-with-25pc-NAs}

# Preparations:

# get all names of variables but exclude criterion: 
column_names_heart <- colnames(heart.train)
column_names_heart <- column_names_heart[column_names_heart != 'diagnosis']


# in total 25%/50%/75% should be NAs in the end, split equally over all variables: 
num_columns <- length(column_names_heart)
pc_per_row_25 <- 0.25

# create vector with that pc for number of rows:
pc_vector_25 <- rep(pc_per_row_25, times = num_columns)

# apply replace_values function and thereby create new data frame:

# set seed for being able to replicate results:
set.seed(13)

# 25% NAs in data set:
heart_NA_25 <- replace_values(data = heart.train, cols = column_names_heart, amount = pc_vector_25)


# build best tree. 25% NAs (standard function)
heart.fft_NA_25 <- FFTrees(formula = diagnosis ~.,
                           data = heart_NA_25,
                           main = "Heart Disease",
                           decision.labels = c("Healthy", "Diseased"))


# Report on NA cases: 
tree_level_outcome_vars <- c(1:3, 7:12, 25:30)
heart.fft_NA_25$trees$level_stats$train[ , tree_level_outcome_vars]
  
plot(heart.fft_NA_25)
```

```{r Data-with-50pc-NAs}

# Preparations:

# get all names of variables but exclude criterion: 
column_names_heart <- colnames(heart.train)
column_names_heart <- column_names_heart[column_names_heart != 'diagnosis']

# in total 50% should be NAs in the end, split equally over all variables: 
num_columns <- length(column_names_heart)
pc_per_row_50 <- 0.50


# create vector with that pc for number of rows:
pc_vector_50 <- rep(pc_per_row_50, times = num_columns)

# apply replace_values function and thereby create new data frame:

# set seed for being able to replicate results:
set.seed(1313)

# 50% NAs in data set:
heart_NA_50 <- replace_values(data = heart.train, cols = column_names_heart, amount = pc_vector_50)



# build best tree, 50% NAs (standard function)
heart.fft_NA_50 <- FFTrees(formula = diagnosis ~.,
                     data = heart_NA_50,
                     main = "Heart Disease",
                     decision.labels = c("Healthy", "Diseased"),
                     do.comp = FALSE)


# Report on NA cases: 
tree_level_outcome_vars <- c(1:3, 7:12, 25:30)
heart.fft_NA_50$trees$level_stats$train[ , tree_level_outcome_vars]
  

plot(heart.fft_NA_50)



```


```{r Data-with-75pc-NAs}


# Preparations:

# get all names of variables but exclude criterion: 
column_names_heart <- colnames(heart.train)
column_names_heart <- column_names_heart[column_names_heart != 'diagnosis']

# in total 75% should be NAs in the end, split equally over all variables: 
num_columns <- length(column_names_heart)
pc_per_row_75 <- 0.75

# create vector with that pc for number of rows:
pc_vector_75 <- rep(pc_per_row_75, times = num_columns)

# apply replace_values function and thereby create new data frame:

# set seed for being able to replicate results:
set.seed(1333)

# 75% NAs in data set:
heart_NA_75 <- replace_values(data = heart.train, cols = column_names_heart, amount = pc_vector_75)



# build best tree, 75% NAs (standard function)
heart.fft_NA_75 <- FFTrees(formula = diagnosis ~.,
                     data = heart_NA_75,
                     main = "Heart Disease",
                     decision.labels = c("Healthy", "Diseased"),
                     do.comp = FALSE)



# Report on NA cases: 
tree_level_outcome_vars <- c(1:3, 7:12, 25:30)
heart.fft_NA_75$trees$level_stats$train[ , tree_level_outcome_vars]
  
plot(heart.fft_NA_75)


```


```{r Data-with-100pc-NAs-in-TESTDATA}


# Preparations:

# get all names of variables but exclude criterion: 
column_names_heart <- colnames(heart.test)
column_names_heart <- column_names_heart[column_names_heart != 'diagnosis']

# in total 100% per row should be NAs in the end: 
per_row_100 <- nrow(heart.test)


# create vector with number of rows:
num_columns <- length(column_names_heart)
vector_100 <- rep(per_row_100, times = num_columns)

# apply replace_values function and thereby create new data frames:

# set seed for being able to replicate results:
set.seed(13)

# 100% NAs in test data set:
heart_NA_100 <- replace_values(data = heart.test, cols = column_names_heart, amount = vector_100)


# Check: 
sum(is.na(heart_NA_100)) == (ncol(heart_NA_100) - 1) * nrow(heart_NA_100)

# build best tree, 100% NAs (standard function)
heart.fft_NA_100 <- FFTrees(formula = diagnosis ~.,
                     data = heart.train,
                     data.test = heart_NA_100,
                     main = "Heart Disease",
                     decision.labels = c("Healthy", "Diseased"),
                     do.comp = FALSE)




# Report on NA cases: 
tree_level_outcome_vars <- c(1:3, 7:12, 25:30)
heart.fft_NA_100$trees$level_stats$test[ , tree_level_outcome_vars]
  
plot(heart.fft_NA_100, data = "test") # it shows the expected behaviour.


```



```{r Data-with-100pc-NAs-in-heartdisease}


# Preparations:

# get all names of variables but exclude criterion: 
column_names_heart <- colnames(heart.test)
column_names_heart <- column_names_heart[column_names_heart != 'diagnosis']

# in total 100% per row should be NAs in the end: 
per_row_100 <- nrow(heart.test)


# create vector with number of rows:
num_columns <- length(column_names_heart)
vector_100 <- rep(per_row_100, times = num_columns)

# apply replace_values function and thereby create new data frames:

# set seed for being able to replicate results:
set.seed(13)

# 100% NAs in test data set:
heart_NA_100 <- replace_values(data = heart.test, cols = column_names_heart, amount = vector_100)


# Check: 
sum(is.na(heart_NA_100)) == (ncol(heart_NA_100) - 1) * nrow(heart_NA_100)

# build best tree, 100% NAs (standard function)
heart.fft_NA_100 <- FFTrees(formula = diagnosis ~.,
                     data = heart.train,
                     data.test = heart_NA_100,
                     main = "Heart Disease",
                     decision.labels = c("Healthy", "Diseased"),
                     do.comp = FALSE)




# Report on NA cases: 
tree_level_outcome_vars <- c(1:3, 7:12, 25:30)
heart.fft_NA_100$trees$level_stats$test[ , tree_level_outcome_vars]
  
plot(heart.fft_NA_100, data = "test") # it shows the expected behaviour.


```
