---
title: "Explore_NAs_additions"
author: "Jelena Meyer"
date: "2023-06-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# load packages
library(FFTrees)

# load replace_values function
replace_values <- function(data, cols, amount, replacement = NA, levels_amount = NULL) {


  # Verify inputs ----
  testthat::expect_true(is.data.frame(data), info = "Data should be a dataframe.") # check that data is a dataframe.
  testthat::expect_true(all(cols %in% names(data)), info = "All column names should be present in the data.") # check that columns is/are all variables in the dataframe.
  testthat::expect_true(length(cols) == length(amount), info = "Number of columns and percentages have to match.") # check if columns and percentages are of the same length.
  testthat::expect_true(all(is.numeric(amount) & (amount >= 0) ), info = "All amounts should be numeric values.") # check that percentages are all numbers between 0 and 1, or higher (than treat as number of to be replaced values.
  testthat::expect_true(is.character(replacement) | is.numeric(replacement) | is.logical(replacement) | is.na(replacement), info = "Replacement value should be of a valid data type (character, nummeric, logical or NA).") # check that replacement is a valid data type.
  testthat::expect_true(is.null(levels_amount) | is.list(levels_amount), info = "levels_amount should be a list") # check that levels_amount is a list if it's not NULL.
  if (!is.null(levels_amount)) {
    testthat::expect_true(all(names(levels_amount) %in% cols), info = "All names in levels_amount have to correspond to a column in the data.") # check if all elements in levels_amount correspond to a column in the data frame.
    for (col in names(levels_amount)) {
      if (is.factor(data[[col]])) {
        testthat::expect_true(all(names(levels_amount[[col]]) %in% levels(data[[col]])), info = "All levels in levels_amount have to be present in the corresponding column of the data.") # check if all sub-elements in each element are valid levels in the corresponding factor variable.

         }

      else if (is.character(data[[col]])) {
        testthat::expect_true(all(names(levels_amount[[col]]) %in% unique(data[[col]])), info = "All levels in levels_amount have to be present in the corresponding column of the data.")

         }

     }

  }


  # loop function over all columns that are inserted in form of a vector and corresponding percentages:
  for (i in seq_along(cols)) {

    col <- cols[i]
    perc <- amount[i]


    # Check if the specific column is a factor and has levels_amount defined:
    if (is.factor(data[[col]]) || is.character(data[[col]]) && !is.null(levels_amount) && col %in% names(levels_amount)) {

      # if all these conditions apply for the column, code is executed:
      # get list of different replacement percentages of levels in column:
      lev_amount <- levels_amount[[col]]

      # loop over levels in current column:
      for (cat in names(lev_amount)) {

        # get replacement percentage for current category:
        replace_perc <- lev_amount[[cat]]

        # get rows in column for current category:
        rows <- which(data[[col]] == cat)

        # Calculate how many values should be replaced in category:
        num_replace <-  ifelse(amount < 1, round(replace_perc * length(rows), 0), amount)


        # Use sample to replace specified percentage of category with replacement input:
        replace_rows <- sample(rows, size = num_replace [1],  replace = FALSE)
        data[replace_rows, col] <- replacement

      }

    } else {

      # Calculate how many values should be replaced:
      num_values <- nrow(data)
      num_replace <-  ifelse(amount < 1, round(amount * num_values, 0), amount)

      # Use sample to replace specified percentage with replacement input:
      replace_rows <- sample(1:num_values,  size = num_replace [1],  replace = FALSE)
      data[replace_rows, col] <- replacement

    }

  }

  # Output: ----

  return(data) # as data frame.

} # replace_values().

```



```{r Baseline}

#Build tree for normal data set


heart.fft <- FFTrees(formula = diagnosis ~.,
                     data = heart.train,
                     data.test = heart.train,
                     main = "Heart Disease",
                     decision.labels = c("Healthy", "Diseased"))

```

# ONLY NUMERIC VARIABLES

```{r add ONLY NUMERIC NAs in data sets}

# Preparations:

# get all names of numeric variables: 
numeric_names_heart <- colnames(heart.train)[sapply(heart.train, is.numeric)]

# in total 10%/20% should be NAs in the end, split  over only numeric variables: 
# count how many values exist in total:
n<- (ncol(heart.train)-1)*nrow(heart.train)

# calculate how many pc per numeric row to add 10%/20% NAs in total:
pc_per_row_10_num <- 0.1*n/length(numeric_names_heart)
pc_per_row_20_num <- 0.2*n/length(numeric_names_heart)


# create vector with that pc for number of rows:
pc_vector_10_num <- rep(pc_per_row_10_num, times = length(numeric_names_heart))
pc_vector_20_num <- rep(pc_per_row_20_num, times = length(numeric_names_heart))


# apply replace_values function and thereby create new data frames:

# set seed for being able to replicate results:
set.seed(13)

# 10% NAs in data set:
heart_NA_10_num <- replace_values(data = heart.train, cols = numeric_names_heart, amount = pc_vector_10_num)
# 20% NAs in data set:
heart_NA_20_num <- replace_values(data = heart.train, cols = numeric_names_heart, amount = pc_vector_20_num)

```


```{r new best trees, 10% NUMERIC NAs}

# build best tree. 10% NUMERIC NAs (standard function):
heart.fft_NA_10_num <- FFTrees(formula = diagnosis ~.,
                     data = heart_NA_10_num,
                     main = "Heart Disease",
                     decision.labels = c("Healthy", "Diseased"))


# Report on NA cases: 
tree_level_outcome_vars <- c(1:3, 7:12, 25:30)
heart.fft_NA_10_num$trees$level_stats$train[ , tree_level_outcome_vars]
  
plot(heart.fft_NA_10_num)


```


```{r new best trees, 20% NUMERIC NAs}

# build best tree, 20% NUMERIC NAs (standard function):
heart.fft_NA_20_num <- FFTrees(formula = diagnosis ~.,
                     data = heart_NA_20_num,
                     main = "Heart Disease",
                     decision.labels = c("Healthy", "Diseased"))


# Report on NA cases: 
tree_level_outcome_vars <- c(1:3, 7:12, 25:30)
heart.fft_NA_20_num$trees$level_stats$train[ , tree_level_outcome_vars]
  

plot(heart.fft_NA_20_num)



```






# ONLY CATEGORIC VARIABLES RANDOMLY!!!

```{r add ONLY CATEGORIC NAs in data sets}

# Preparations:

# get all names of CATEGORIC variables: 
categoric_names_heart <- colnames(heart.train)[sapply(heart.train, is.character)]

# in total 10%/20% should be NAs in the end, split  over only categoric variables: 
# count how many values exist in total:
n<- (ncol(heart.train)-1)*nrow(heart.train)

# calculate how many pc per categoric row to add 10% NAs in total:
pc_per_row_10_cat <- 0.1*n/length(categoric_names_heart)
pc_per_row_20_cat <- 0.2*n/length(categoric_names_heart)


# create vector with that pc for number of rows:
pc_vector_10_cat <- rep(pc_per_row_10_cat, times = length(categoric_names_heart))
pc_vector_20_cat <- rep(pc_per_row_20_cat, times = length(categoric_names_heart))

# apply replace_values function and thereby create new data frames:

# set seed for being able to replicate results:
set.seed(13)

# 10% NAs in data set:
heart_NA_10_cat <- replace_values(data = heart.train, cols = categoric_names_heart, amount = pc_vector_10_cat)
# 20% NAs in data set:
heart_NA_20_cat <- replace_values(data = heart.train, cols = categoric_names_heart, amount = pc_vector_20_cat)

```


```{r new best trees, 10% CATEGORIC NAs}

# build best tree. 10% CATEGORIC NAs (standard function):
heart.fft_NA_10_cat <- FFTrees(formula = diagnosis ~.,
                     data = heart_NA_10_cat,
                     main = "Heart Disease",
                     decision.labels = c("Healthy", "Diseased"))


# Report on NA cases: 
tree_level_outcome_vars <- c(1:3, 7:12, 25:30)
heart.fft_NA_10_cat$trees$level_stats$train[ , tree_level_outcome_vars]
  
plot(heart.fft_NA_10_cat)


```



```{r new best trees, 20% CATEGORIC NAs}

# build best tree. 20% CATEGORIC NAs (standard function):
heart.fft_NA_20_cat <- FFTrees(formula = diagnosis ~.,
                     data = heart_NA_20_cat,
                     main = "Heart Disease",
                     decision.labels = c("Healthy", "Diseased"))


# Report on NA cases: 
tree_level_outcome_vars <- c(1:3, 7:12, 25:30)
heart.fft_NA_20_cat$trees$level_stats$train[ , tree_level_outcome_vars]
  
plot(heart.fft_NA_20_cat)


```






