# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' classtableC
#'
#' this does something
#'
#' @export
classtableC <- function(pred, crit) {
    .Call('FFTrees_classtableC', PACKAGE = 'FFTrees', pred, crit)
}

timesTwo <- function(x) {
    .Call('FFTrees_timesTwo', PACKAGE = 'FFTrees', x)
}

