# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' classtableC
#'
#' Calculates several classification statistics from binary prediction and criterion (e.g.; truth) vectors
#' @param pred A binary vector of predictions
#' @param crit A binary vector of criterion (true) values
#' @export
classtableC <- function(pred, crit) {
    .Call('FFTrees_classtableC', PACKAGE = 'FFTrees', pred, crit)
}

